### PR TITLE
User management

### PR DESCRIPTION
**Pull request by bnmajor**
Displays the user profile created in OpenChemistry/oc-web-components#128

### CODE REVIEW

**Comment by cjh1** [comment]
I am getting 

```
Module not found: Can't resolve './user/containers/password' in '/home/cjh/work/source/oc-web-components/packages/girder-ui/esm'
```

when I try to run, it looks like the oc-web-components branch may have some leftover imports or is missing a file?

**Comment by bnmajor** [comment]
There was indeed a leftover import from a removed file, sorry about that. The import has been removed on the oc-web-components branch.

**Comment by cjh1** [comment]
@bnmajor Can we fix these conflicts?

**Comment by bnmajor** [comment]
@cjh1 Sorry about that, apparently I never pushed that commit. Merge conflicts have been resolved.

**Comment by cjh1** [comment]
No problem, will try it out now.

**Review by cjh1 — APPROVED** [review]
This is working well now, thank you. I bumped the openchemistry package versions, so we should be good to go.

**Comment by cjh1** [comment]
@bnmajor I resolved the conflicts I caused with master :smile:

**Pull request merged**
