### PR TITLE
Upload Calculation via File

### PR DESCRIPTION
**Pull request by bnmajor**
Allows a user to select and upload a `cjson` file containing a calculation. Files can currently be uploaded either from an individual molecule page or from the My Calculations page. Uploading a file will automatically create the molecule if it does not already exist, or associate the calculation with the correct molecule if it does.

For example, uploading a calculation for Decane from Nonane's molecule page will still associate the calculation with Decane.

### CODE REVIEW

**Comment by bnmajor** [comment]
mycalcs_upload
mols_uploadCalc

**Comment by bnmajor** [comment]
These changes work with changes made in openchemistry/oc-web-components#153 and openchemistry/mongochemserver#170

**Comment by cjh1** [comment]
@bnmajor Is appears that the cancel button doesn't seem todo anything?

**Comment by cjh1** [comment]
Does the file that was uploaded get deleted after the calculation has been ingested?

**Comment by cjh1** [comment]
@bnmajor When you get a chance could answer my question? Other than this, is this ready to go?

**Comment by bnmajor** [comment]
@cjh1 Looks like a change got lost along the way, but the cancel button should work now.

The file that is being uploaded into Girder is not deleted from Girder after ingestion - should it be?

Everything else should be working and ready to go, other than deleting the ingested file.

**Review by cjh1 — APPROVED** [review]
LGTM, works as designed, thanks!

**Comment by bnmajor** [comment]
@cryos Fixed some merge conflicts and added a fix to clean up a console warning, but otherwise this seems to still be good to go. Tested locally with no issues. Goes with the instructions added in OpenChemistry/mongochemdeploy#101

**Pull request merged**
