### PR TITLE
Mols and cals by user

### PR DESCRIPTION
**Pull request by bnmajor**
Add the ability to view only the calculations and/or molecules created by the current user.

Relies on changes made in openchemistry/oc-web-components#134

### CODE REVIEW

**Comment by bnmajor** [comment]
This seems to be working, but all of the users I have to test this with either have none or all of the calculations/molecules, so additional testing should be done.

**Comment by cjh1** [comment]
@bnmajor Can you please fix this conflict.

**Comment by cjh1** [comment]
@bnmajor I have also merged and released the changes in oc-web-components, so you can update the `package.json` accordingly here.

**Comment by bnmajor** [comment]
Sorry about that, conflict has been fixed. The `package.json` dependencies have also been updated.

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
