### PR TITLE
Use names for card titles

### PR DESCRIPTION
**Pull request by psavery**
Signed-off-by: Patrick Avery <patrick.avery@kitware.com>

### CODE REVIEW

**Comment by psavery** [comment]
Since the user can now set names in the notebook using `set_name()`, should we use the names for the card titles like this? Some examples are shown below.

Screenshot from 2019-03-27 19-45-54
Screenshot from 2019-03-27 19-45-46

If the user doesn't explicitly set a name, it gets set to the formula as far as I can tell.

**Comment by alesgenova** [comment]
@psavery 
It's good to have the name displayed if available, but this PR is removing the formula as a fall back.
Before:
`formula -> 'Calculation'`

Now:
`name -> 'Calculation'`

Should be:
`name -> formula -> 'Calculation'`

**Comment by psavery** [comment]
Okay. I can add the formula fallback. Although, I should warn that with our current mongochemserver, I think every molecule is given a name. If `molecule.name` isn't set by the user, it defaults to its chemical formula [here](https://github.com/OpenChemistry/mongochemserver/blob/master/girder/molecules/server/utilities/molecules.py#L79) and [here](https://github.com/OpenChemistry/mongochemserver/blob/master/girder/molecules/server/chemspider.py#L15).

**Comment by alesgenova** [comment]
I see then I guess it's not really needed.
However, if the formula is set as a name fallback on the server, we miss the formatting on the clientside.
I.e. C6H6 will be shown as is, instead of going through the `formatFormula()` function that would make the numbers appear as subscripts

**Comment by psavery** [comment]
Yeah. Maybe we should remove the formula as the default for the name on the server?

**Comment by alesgenova** [comment]
Yeah, if we are aware that name may or may not be there, it's easier to deal with it

**Comment by cryos** [comment]
Agreed, and falling back to a properly formatted formula would be preferred.

**Comment by psavery** [comment]
In the example posted below, I set the name for caffeine, but did not set a name for water. As you can see, the title for water is the formatted formula, and the title for caffeine is its name.

This behavior is the same for the other cards page and the calculation and molecule pages.

Screenshot from 2019-03-28 12-59-40

**Comment by psavery** [comment]
I might want to double-check it one more time though...

**Comment by cryos** [comment]
That looks great, and would be the preferred functionality.

**Comment by psavery** [comment]
I double-checked it, and I think it works as intended.

**Review by alesgenova — APPROVED** [review]

**Pull request merged**
